### ISSUE TITLE
Project idea: guides

### ISSUE THREAD

**Issue by NyCodeGHG** [Paul2708/spigot-plugin-resources#17]
What do you think about adding a folder like "guides" or something like this and add tutorials or guides for example for setting up a development environment or setting up a server or network correctly etc.

Example:

* 📁 **guides**
  * 📑 **setup-dev-environment.md**
  * 📑 **setup-a-server.md**
  * 📑 **setup-server-docker.md**
  * 📑 **scheduler-guide.md**
  * 📑 **commands-guide.md**
  * 📑 **README.md** (Index with links to all guides)
* 📑 api-repository.md
* 📑 requirements.md
* 📑 servers.md

**Comment by Paul2708** [comment]
I think that this would be a great addition to this repository!
It looks like you already got some nice ideas. If you have some free time, can you open a second issue that lists your guide ideas with a short description and what the goal is?

However, Spigot already has a wiki section (cf. [https://www.spigotmc.org/wiki/](https://www.spigotmc.org/wiki/)) and I don't want to mirror them. So especially, I think that "new" guides like `setup-server-docker` or `setup-dev-env` are more interesting.
