### ISSUE TITLE
Where to put external applications?

### ISSUE THREAD

**Issue by Paul2708** [Paul2708/spigot-plugin-resources#19]
I found [MC-Auth](https://github.com/Mc-Auth-com/Mc-Auth/) that allows an "easily login with your Minecraft account without giving your password or email to strangers – Fully OAuth 2.0 compliant!"

I'd like to add it to the repository but it's not an API, therefore, `api-repository.md` seems not to be the right place for it.

Do you have an idea where to put it? Maybe the section could fit other external applications as well.

**Comment by NyCodeGHG** [comment]
I think a new file for 'External (minecraft related) software' would be good. So we put in MC-Auth and other things like [CloudNet](https://github.com/CloudNetService/CloudNet-v3) there.

**Comment by Paul2708** [comment]
There is now a new chapter called [`External Applications`](https://github.com/Paul2708/spigot-plugin-resources/blob/master/chapters/applications.md). Feel free to add CloudNet :)
